import {
  AmericanoIcon,
  SmoothieOrangeIcon,
  SmoothiePineappleIcon,
  SmoothieStrawberryIcon,
  EspressoDopioIcon,
  EspressoIcon,
  LatteMacchiatoIcon,
  FlatWhiteIcon,
  EspressoMacchiatoIcon,
  EspressoMacchiatoIcon2,
  CappuccinoIcon,
  CoffeeCupIcon,
  CupIcon,
  CoffeeIcon,
  FrappuccinoIcon,
  WaffleIcon,
  ChocolateWaffleIcon,
  BerryWaffleIcon,
  WhiteWineIcon,
  SmoothieAppleIcon,
} from "@/components/icons";

const iconMap: { [key: string]: any } = {
  "Double Espresso": EspressoDopioIcon,
  Espresso: EspressoIcon,
  Ristretto: EspressoIcon,
  Mochaccino: FlatWhiteIcon,
  "Various teas": CupIcon,
  "SMS Espresso": EspressoIcon,
  Americano: AmericanoIcon,
  "Latte Macchiato": LatteMacchiatoIcon,
  "Caffè Latte": LatteMacchiatoIcon,
  "Cafè Latte": LatteMacchiatoIcon,
  "Twilio Latte": LatteMacchiatoIcon,
  "Flat White": FlatWhiteIcon,
  Macchiato: EspressoMacchiatoIcon,
  "Money Macchiato": EspressoMacchiatoIcon,
  "Double Macchiato": EspressoMacchiatoIcon2,
  Cappuccino: CappuccinoIcon,
  "Cloud Cappuccino": CappuccinoIcon,
  "Espresso Macchiato": EspressoMacchiatoIcon2,
  Coffee: CoffeeIcon,
  Matcha: CoffeeCupIcon,
  Chocolate: CoffeeCupIcon,
  "Hot Chocolate": CoffeeCupIcon,
  Latte: LatteMacchiatoIcon,
  Mocha: CupIcon,
  "Iced Latte": FrappuccinoIcon,
  "Iced Americano": FrappuccinoIcon,
  "Iced Matcha": FrappuccinoIcon,
  "Black Tea": CupIcon,
  "British Breakfast Tea": CupIcon,
  "Apple Chamomile": CupIcon,
  "Earl Grey": CupIcon,
  "Herbal Tea": CupIcon,
  Chai: CupIcon,
  "Chai Latte": CupIcon,
  "Matcha Latte": CupIcon,
  "Espresso Martini": WhiteWineIcon,
  "Maracuia Fitzgerald": WhiteWineIcon,
  Negroni: WhiteWineIcon,
  Macunaíma: WhiteWineIcon,
  Especiado: WhiteWineIcon,
  Verdejo: WhiteWineIcon,
  "White Russian": WhiteWineIcon,
  "Hot White Russian": WhiteWineIcon,
  "Irish Coffee": WhiteWineIcon,
  "Café Colada": FlatWhiteIcon,
  Cortadito: FlatWhiteIcon,
  Cortado: FlatWhiteIcon,
  "Caramelo Cortado": FlatWhiteIcon,
  "Café Con Leche": FlatWhiteIcon,
  "Café Dulce": FlatWhiteIcon,
  "Café Coco": FlatWhiteIcon,
  "Con Sabor": FlatWhiteIcon,
  Mudslide: WhiteWineIcon,
  Cosmopolitan: WhiteWineIcon,
  Cosmo: WhiteWineIcon,
  Appletini: WhiteWineIcon,
  "Irish Lovers": WhiteWineIcon,
  "Shakerato Lovers": WhiteWineIcon,
  "Blue Gin Lovers": WhiteWineIcon,
  "Mango Black Tea": CupIcon,
  "Lychee Peachy Green Tea": CupIcon,
  "Caramel Milk Tea": CupIcon,
  "Strawberry Matcha Latte": CupIcon,
  "Strawberry Lemonade Tea": CupIcon,
  "Cold Brew": CupIcon,
  Moka: FlatWhiteIcon,
  "Espresso Chantilly": EspressoIcon,
  "Matcha Green Tea": CupIcon,
  "Cucumber Juice": CupIcon,
  Nuttello: WaffleIcon,
  Banoffo: WaffleIcon,
  Oreo: ChocolateWaffleIcon,
  Snikero: ChocolateWaffleIcon,
  "Vegan Delight": BerryWaffleIcon,
  Macarena: SmoothieStrawberryIcon,
  "La Isla Bonita": SmoothiePineappleIcon,
  Calma: SmoothieAppleIcon,
  "Des.pa.cito": SmoothieAppleIcon,
  "Berry Burst": SmoothieStrawberryIcon,
  "Passion Storm": SmoothieOrangeIcon,
  "Mango Dream": SmoothiePineappleIcon,
  "Strawberry Delight": SmoothieStrawberryIcon,
  "Green Reviver": SmoothieAppleIcon,
  "Ginger Beets": SmoothieStrawberryIcon,
};

export default iconMap;
