import {
  AmericanoIcon,
  SmoothieOrangeIcon,
  SmoothiePineappleIcon,
  SmoothieStrawberryIcon,
  EspressoDopioIcon,
  EspressoIcon,
  LatteMacchiatoIcon,
  FlatWhiteIcon,
  EspressoMacchiatoIcon,
  EspressoMacchiatoIcon2,
  CappuccinoIcon,
  CoffeeCupIcon,
  CupIcon,
  CoffeeIcon,
  FrappuccinoIcon,
  CarafeIcon,
  WhiteWineIcon,
} from "@/components/icons";

const iconMap: { [key: string]: any } = {
  "Double Espresso": EspressoDopioIcon,
  Espresso: EspressoIcon,
  Americano: AmericanoIcon,
  "Latte Macchiato": LatteMacchiatoIcon,
  "Caffè Latte": LatteMacchiatoIcon,
  "Flat White": FlatWhiteIcon,
  Macchiato: EspressoMacchiatoIcon,
  "Double Macchiato": EspressoMacchiatoIcon2,
  Cappuccino: CappuccinoIcon,
  "Espresso Macchiato": EspressoMacchiatoIcon2,
  Coffee: CoffeeIcon,
  Matcha: CoffeeCupIcon,
  Chocolate: CoffeeCupIcon,
  Mocha: CupIcon,
  "Iced Latte": FrappuccinoIcon,
  "Iced Americano": FrappuccinoIcon,
  "Black Tea": CupIcon,
  "British Breakfast Tea": CupIcon,
  "Apple Chamomile": CupIcon,
  "Earl Grey": CupIcon,
  "Herbal Tea": CupIcon,
  Chai: CupIcon,
  "Chai Latte": CupIcon,
  "Matcha Latte": CupIcon,
  Colombia: SmoothieStrawberryIcon,
  Aquamarine: SmoothiePineappleIcon,
  Lambada: SmoothieOrangeIcon,
  "Espresso Martini": WhiteWineIcon,
  "White Russian": CarafeIcon,
  "Irish Coffee": CarafeIcon,
  "Café Colada": FlatWhiteIcon,
  Cortadito: FlatWhiteIcon,
  Cortado: FlatWhiteIcon,
  "Caramelo Cortado": FlatWhiteIcon,
  "Café Con Leche": FlatWhiteIcon,
  "Café Dulce": FlatWhiteIcon,
  "Café Coco": FlatWhiteIcon,
  "Con Sabor": FlatWhiteIcon,
  Mudslide: CarafeIcon,
  "Mango Black Tea": CupIcon,
  "Lychee Peachy Tea": CupIcon,
  "Caramel Milk Tea": CupIcon,
};

export default iconMap;
